// Código generado automáticamente. No editar.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "cat0":return img`
eeeeeeeee.eeeee....eeeeeeeeee...........
eeeeeeeee..........eeeeeeeeee...........
cccddddddcc......ccddddddcccc...........
cccddddddcc......ccddddddcccc...........
cccbbddddddffffffddddddbbcccc...........
cccbbddddddffffffddddddbbcccc...........
cccbbddddddffffffddddddbbcccc...........
cccbbddddddffffffddddddbbcccc...........
ccc33bbbbddddddbbddbbbb33cccc...........
ccc33bbbbddddddbbddbbbb33cccc...........
fffbb3333dddddddddd3333bbffff...........
fffbb3333dddddddddd3333bbffff...........
fffbb3333dddddddddd3333bbffff...........
fffbb3333dddddddddd3333bbffff...........
fffbb3333dddddddddd3333bbffff...........
eeeddddddddddddddddddddddeeee...........
eeeddddddddddddddddddddddeeee...........
eeeddffffddddddddddffffddeeee..bbbbffbb.
eeeddffffddddddddddffffddeeee..bbbbffbb.
fffddddddffddddddffddddddffff..ffffddff.
fffddddddffddddddffddddddffff..ffffddff.
fffddddddffddddddffddddddffff..ffffddff.
fffddddddffddddddffddddddffff..ffffddff.
fffbbddddddbbbbbbdddddd22ffff..ffffddff.
fffbbddddddbbbbbbdddddd22ffff..ffffddff.
...ff222222222222222222bbbbbbffffffddff.
...ff222222222222222222bbbbbbffffffddff.
...ff222222222222222222bbbbbbffffffddff.
...ff222222222222222222bbbbbbffffffddff.
...ff222222222222222222bbbbbbffffffddff.
...ffbbbbddddddddddddddddbbbbbbddddbbff.
...ffbbbbddddddddddddddddbbbbbbddddbbff.
...ffddddddddddddddbbbbddddddffffffff...
...ffddddddddddddddbbbbddddddffffffff...
...ffddddddddddddddbbbbddddddffffffff...
...ffddddddddddddddbbbbddddddffffffff...
...ffddddffffffffddffffffddddff.........
...ffddddffffffffddffffffddddff.........
...ffffff......ffff......ffffff.........
...ffffff......ffff......ffffff.........
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Código generado automáticamente. No editar.
